### ISSUE TITLE
Can't add words to dictionary

### ISSUE THREAD

**Issue by daniel-sousa-me** [ibus/ibus-anthy#30] opened 2022-07-26 17:12 UTC
Which distribution and version?: Debian testing

Which desktop environment and version?: xmonad

Which session type?: X11

Which application and version?: kasumi

IBus version?: IBus 1.5.26

ibus-anthy version?: 1.5.14

Issue description: 
When I try to add a new word with kasumi I get the error "Failed to register"

Steps to reproduce:
1. Run `kasumi -a`
2. Try to add some word
3. Save

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by daniel-sousa-me** [comment] 2022-07-26 17:13
In the terminal I get a segmentation fault

**Comment by fujiwarat** [comment] 2022-07-28 10:05
What is ANTHY_PC in your pacakge?
``` 
% grep ANTHY_PC /usr/share/ibus-anthy/engine/_config.py
```

**Comment by daniel-sousa-me** [comment] 2022-07-28 10:18
`ANTHY_PC= 'anthy'`

**Comment by fujiwarat** [comment] 2022-07-29 08:36
I cannot reproduce your problem.

> When I try to add a new word with kasumi I get the error "Failed to register"

Do you mean kasumi said that error instead of ibus-anthy?

> In the terminal I get a segmentation fault

Do you mean kasumi became the SEGV?

**Comment by daniel-sousa-me** [comment] 2022-07-29 13:21
Is kasumi not part of anthy? I think the problem is with kasumi. Can I bypass the interface and somehow add words manually?

**Comment by fujiwarat** [comment] 2022-07-29 15:02
> Is kasumi not part of anthy?

No.

>  I think the problem is with kasumi. 

I'm still doubt what is your issue. Can you get the the stack trace of your SEGV with gdb?

> Can I bypass the interface and somehow add words manually?

You can see $HOME/.anthy/private_words_default

**Comment by fujiwarat** [comment] 2022-08-01 13:51
No reply, closing

**Closed** 2023-01-26 08:48 UTC
